name: E2E on Prd Chrome
on: push
  # workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Prd Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
           browser: chrome
           env: Environment = prd
        #      Notes=${{ secrets.SECRETS1 }}
           config-file: prodenv-config.json
           spec: cypress/integration/1-getting-started/specimen.js
           
        env:
          CYPRESS_Notes: ${{ secrets.SECRETS2 }}
      - name: Cypress Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: screenshots-in-chrome
          path: cypress/screenshots
      #    browser: chrome
      #    record: true
      #    group: Tests on Chrome
      #    env: lastName=Smith
      #  env:
      #    CYPRESS_firstName: Joe
      #    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            
